package com.alekso.dltparser.dlt.extendedheader

enum class MessageTypeInfo {
    DLT_LOG_FATAL,
    DLT_LOG_DLT_ERROR,
    DLT_LOG_WARN,
    DLT_LOG_INFO,
    DLT_LOG_DEBUG,
    DLT_LOG_VERBOSE,
    DLT_LOG_RESERVED,

    DLT_TRACE_VARIABLE,
    DLT_TRACE_FUNCTION_IN,
    DLT_TRACE_FUNCTION_OUT,
    DLT_TRACE_STATE,
    DLT_TRACE_VFB,
    DLT_TRACE_RESERVED,

    DLT_NW_TRACE_IPC,
    DLT_NW_TRACE_CAN,
    DLT_NW_TRACE_FLEXRAY,
    DLT_NW_TRACE_MOST,
    DLT_NW_TRACE_ETHERNET,
    DLT_NW_TRACE_SOMEIP,
    DLT_NW_TRACE_USER_DEFINED,

    DLT_CONTROL_REQUEST,
    DLT_CONTROL_RESPONSE,
    DLT_CONTROL_RESERVED,

    UNKNOWN,
}