# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Release Artifacts

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build .dmg
        run: ./gradlew packageDmg

      - name: Find generated files
        run: find build -type f

      - name: Upload .dmg to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: desktop-app/build/compose/binaries/main/dmg/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build .msi and .exe
        run: |
          ./gradlew packageMsi
          ./gradlew packageExe

      - name: Find generated files
        run: Get-ChildItem -Recurse build | Format-List FullName

      - name: Upload .msi and .exe to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            desktop-app/build/compose/binaries/main/msi/*.msi
            desktop-app/build/compose/binaries/main/exe/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build .deb
        run: ./gradlew packageDeb

      - name: Find generated files
        run: find build -type f

      - name: Upload .deb to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: desktop-app/build/compose/binaries/main/deb/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}